### ISSUE TITLE
Error with RA 

### ISSUE THREAD

**Issue by djoveryde** [CreativeMD/RandomAdditions#17]
This happend when I try to look into a recipe for "Tourmaline" from "Random Additions" with NEI. Couldnt reproduce this crash yet.
============================================================================
java.lang.IndexOutOfBoundsException: Index: 4, Size: 0

    at java.util.ArrayList.rangeCheck(-1)
    at java.util.ArrayList.get(-1)
    at com.creativemd.randomadditions.common.item.tools.Tool.getIcon(Tool.java:88)
    at com.creativemd.randomadditions.common.item.ItemTool.getIcon(ItemTool.java:332)
    at com.creativemd.randomadditions.common.item.ItemTool.func_77650_f(ItemTool.java:325)
    at net.minecraft.item.ItemStack.func_77954_c(ItemStack.java:117)
    at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:403)
    at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
    at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1357)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke(-1)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(-1)
    at java.lang.reflect.Method.invoke(-1)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by CreativeMD** [comment]
I tried it, but everything worked fine, if it happens again please let me know, but for now i will close this issue.

**Comment by djoveryde** [comment]
Not sure if this issue occurs with cauldron only as that's what I'm using server side.

**Comment by CreativeMD** [comment]
But looking up a recipe is client side :O
