### ISSUE TITLE
Ticking memory connection

### ISSUE THREAD

**Issue by sysm789** [CreativeMD/RandomAdditions#23]
When I tray 30 min place watermill i have crashed ...

* CreativeCore v1.3.9 mc1.7.10.jar
* RandomAdditions Alpha 0.11.12 mc1.7.10.jar

----------------------------------------------------------------------------------------
[04/10/2015 12:10:38 PM] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[04/10/2015 12:10:39 PM] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer
[04/10/2015 12:10:45 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.gui.GuiContainerSub
[04/10/2015 12:10:45 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.container.ContainerSub
[04/10/2015 12:11:02 PM] [Client thread/INFO] [inventorytweaks]: net.minecraft.client.gui.inventory.GuiInventory
[04/10/2015 12:11:03 PM] [Client thread/INFO] [inventorytweaks]: net.minecraft.inventory.ContainerPlayer
[04/10/2015 12:11:50 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.gui.GuiContainerSub
[04/10/2015 12:11:51 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.container.ContainerSub
[04/10/2015 12:11:52 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.gui.GuiContainerSub
[04/10/2015 12:11:52 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.container.ContainerSub
[04/10/2015 12:12:01 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.gui.GuiContainerSub
[04/10/2015 12:12:01 PM] [Client thread/INFO] [inventorytweaks]: com.creativemd.creativecore.common.container.ContainerSub
[04/10/2015 12:12:04 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[04/10/2015 12:12:04 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '3ac693e1-ff15-4d0c-b592-181519e785f0' not found in method 'play'
[04/10/2015 12:12:04 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[04/10/2015 12:12:04 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '125e8124-28ce-4614-b1b1-76598e9d1fe5' not found in method 'play'
[04/10/2015 12:12:04 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[04/10/2015 12:12:04 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '62ff6c2f-4aa1-49fe-aa8f-bd64e1fb8d5d' not found in method 'play'
[04/10/2015 12:12:05 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[04/10/2015 12:12:05 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '3ac693e1-ff15-4d0c-b592-181519e785f0' not found in method 'play'
[04/10/2015 12:12:05 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[04/10/2015 12:12:05 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '125e8124-28ce-4614-b1b1-76598e9d1fe5' not found in method 'play'
[04/10/2015 12:12:05 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:131]: Error in class 'LibraryLWJGLOpenAL'
[04/10/2015 12:12:05 PM] [12:12:04] [Thread-47/INFO] [STDOUT]: [paulscode.sound.SoundSystemLogger:errorMessage:132]:     Source '62ff6c2f-4aa1-49fe-aa8f-bd64e1fb8d5d' not found in method 'play'
[04/10/2015 12:12:05 PM] [Server thread/ERROR]: Encountered an unexpected exception
[04/10/2015 12:12:05 PM] net.minecraft.util.ReportedException: Ticking memory connection
[04/10/2015 12:12:05 PM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) ~[nc.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) ~[bsx.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[04/10/2015 12:12:05 PM] Caused by: java.lang.NullPointerException
[04/10/2015 12:12:05 PM] 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:620) ~[nh.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60) ~[jo.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9) ~[jo.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
[04/10/2015 12:12:05 PM] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
[04/10/2015 12:12:05 PM] 	... 5 more

**Comment by CreativeMD** [comment]
Could you please send me the full crash report?

**Comment by sysm789** [comment]
I'm sorry, I can't find crash file. I updated version, and everything is fine. 

I am grateful to you for your work.

Awesome mod!

**Comment by CreativeMD** [comment]
Ok nice
